### ISSUE TITLE
Implement measures checks 

### ISSUE THREAD

**Issue by OkonSamuel** [JuliaAI/MLJEnsembles.jl#20]
We need to Implement measures checks for measures passed to `out_of_bag_measure` parameter of `EnsembleModel`.  
Currently any `Vector` of Julia objects can be passed as input to the `out_of_bag_measure` parameter of `EnsembleModel`, whereas this should only allow passing a vector of MLJ measures.
Also, the current implementation allows observation weights to be passed to any measure, even those measures supporting only class-weights. Hence checks should be implemented to avoid this and throw an informative error message.
Finally, users can even pass measures that are only valid for classifiers to `DeterministicEnsembleModels` making deterministic predictions. Check have to be implemented to avoid this also.

These checks could be similar to the one found [here](https://github.com/JuliaAI/MLJBase.jl/blob/dev/src/resampling.jl#L604-L657)

**Comment by ablaom** [comment]
Closing in favour of #26.
